### ISSUE TITLE
Text Overlapping on publications

### ISSUE THREAD

**Issue by jamesfinnerty** [lensterxyz/lenster#1922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Brave mobile, iOS 16.2

Text on some posts are overlapping. See image attached. 
![74A79865-C312-4096-B59A-31EC8D34EA56](https://user-images.githubusercontent.com/88593099/224057803-cc8ff32e-8c2d-4954-b0b0-57beece82682.png)

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Brave

**Comment by blackshor** [comment]
I'm sorry to hear that you're experiencing issues with text overlapping on some posts in Brave mobile on iOS 16.2. This could be caused by a few different things, including:

A bug in the app
An issue with the website's code or layout
A problem with the font or font size settings on your device
Here are a few things you can try to fix the issue:

Try closing and reopening the app to see if that resolves the issue.
Check for any available updates for the Brave app in the App Store and install them if there are any.
If the issue is only occurring on certain websites, try clearing your cache and cookies for those sites. You can do this by going to Settings > Safari > Clear History and Website Data.
Adjust the font size settings on your device to see if that helps. Go to Settings > Display & Brightness > Text Size and drag the slider to adjust the font size.
If none of these solutions work, it may be worth contacting Brave support for further assistance.

**Comment by foolo** [comment]
https://lenster.xyz/posts/0x019aac-0x60

**Comment by foolo** [comment]
I tried it in Brave and it looks good for me. See screenshot.
@jamesfinnerty I think this issue is resolved. You could check again and verify, https://lenster.xyz/posts/0x019aac-0x60

![2023-05-27 17 57 52](https://github.com/lensterxyz/lenster/assets/667227/26621149-003f-42e5-9fdd-b4ef3fc62d31)

**Comment by jamesfinnerty** [comment]
Cool, thanks! I haven't noticed it lately. I still see it happen next to some markup text or emojis, but haven't seen the original bug replicating.

**Comment by foolo** [comment]
@jamesfinnerty Ok thanks! I'll close this one. Feel free to open a new issue for the problems you mentioned regarding markup text or emojis
